---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: traefik-sandbox
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: traefik-sandbox-api:latest
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: traefik-sandbox
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: traefik-sandbox-echo:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: traefik-sandbox
spec:
  selector:
    app: echo
  ports:
    - name: http
      protocol: TCP
      port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: traefik-sandbox
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 8000

